version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./go
    ports:
      - "9000:9000"

  web:
    build:
      dockerfile: Dockerfile
      context: ./typescript/simple-mercari-web
    ports:
      - "3000:3000"
